#Std units: mA, V, mW, nm

[measurement]
Type = "spr_no_lam_vcsel_sweep"
dc_unit = "keithley2400"    # DC power supply
v_max = 5                   # Max allowed voltaged

save_folder = "SPR_measurements" # Save folder
spr_measurement_name = "mindaugas_makes_everything_work_great"

check_bias           = 1    # Bias current to check the alignment
measurement_time     = 10   # Measurement time in seconds
measurement_interval = 1    # Take a picture every x sec
exposure_time        = 0.03 # Exposure time in sec

find_det_lines       = 0    # Run live capturing to find detection line
find_line_biased     = 0    # Run live capturing with biased VCSEL

vcsel_chip           = "johannes" # Which chip is being used
vcsel_biases         = [1, 1, 1]  # mA

verbose_printing     = 1        # Flag for printing

[keithley2400]
Type = "keithley2400"       # The specific type of unit
GPIB_address = "24"
