# Std units: mA, V, mW, nm

[measurement]
Type = "spr_no_lam_vcsel_sweep"
#Type = "spr_alignment"
dc_unit = "keithley2400"    # DC power supply
v_max = 5                   # Max allowed voltaged

#Saving stuff
save_folder = "SPR_measurements_240123" # Save folder
spr_measurement_name = "miRNA_DNA_attempt_4"
#spr_measurement_name = "y_max_ref"
save_raw_images = 0

# VCSEL parameters
vcsel_chip           = "sigge" # Which chip is being used
vcsel_biases         = [2, 2, 5]  # mA
vcsel_array_bias     = 7

# Camera and measurement interval
measurement_time            = 15000   # Measurement time in seconds
measurement_interval        = 1.5      # Take a picture every x sec
measurement_subinterval     = 0.001  
exposure_time               = 0.01   # Exposure time in sec
frame_average_buffer        = 10
frame_average               = 10

verbose_printing     = 1        # Flag for printing

[keithley2400]
Type = "keithley2400"       # The specific type of unit
GPIB_address = "24"
