[measurement]
Type = "ipv"
Save_folder = "c:/LABDATA"
DC_unit = "keithley2400"
P_unit = "INT_sphere"
V_max = 5
Rollover_threshold = 0
Rollover_min = 0.1
Current = [[0.001, 0.0001, 0.005], [0.005, 0.0005, 0.015]]

[keithley2400]
GPIB_address = "24"

[INT_sphere]
Range = 2
Min_measure_time = 0.2
Wavelength = 5

[powercube]
Port = "com4"