[measurement]
type = "ipv"
DC_unit = "keith"
P_unit = "INT_sphere"
V_max = 5
P_cutoff = 0
current = [[0.001, 0.0001, 0.005], [0.005, 0.0005, 0.015]]


[keith]
type = "keithley"
address = "24"

[INT_sphere]
type = "INT_sphere"
range = 2
min_measure_time = 0.2
