# Std units: mA, V, mW, nm
[measurement]
type = "SPR_CH1"
#type = "spr_no_lam_vcsel_sweep"
dc_unit = "keithley2400"    # DC power supply
v_max = 5                   # Max allowed voltaged

# Saving stuff
# Spr_measurement_name = "test"
measurement_name = "test_run"
save_raw_images = 0

# What to do in the script
run_measurement = 1

# Save the integrated y spectrum for each time point?
save_y_spectrum = 1 

# What region to use in second image while measuring
start_cropped_image_from = 500
stopp_cropped_image_from = 4000

# What region to use in third image for searching for SPR dip (IMPORTANT THAT THE SPR DIP IS THE MINIMUM!)
start_look_for_dip_from  = [2200, 800, 2200, 2200]
stopp_look_for_dip_from  = [2800, 1400, 2800, 2800]

# Width around the dip to interpolate over. Larger = better
width_around_SPR_dip_um = 50
# VCSEL parameters
vcsel_chip           = "karola_top" # Which chip is being used

# A0, A2, C3, D1
vcsel_biases         = [4.9, 4.4, 3.1, 2.5]  # mA
vcsel_array_bias     = 7

# Camera and measurement interval
measurement_time            = 10000   # Measurement time in seconds
measurement_interval        = 1.0     # Take a picture every x sec
exposure_time               = 0.2     # Exposure time in sec
integrate_over_um           = 100

verbose_printing     = 1        # Flag for printing

[dc_unit]
#type = "dummy"
type = "keithley2400"       # The specific type of unit
GPIB_address = "24"