# Std units: mA, V, mW, nm

[measurement]
Type = "spr_no_lam_vcsel_sweep"
dc_unit = "keithley2400"    # DC power supply
v_max = 5                   # Max allowed voltaged

# Saving stuff
save_folder = "SPR_measurements_231027" # Save folder
spr_measurement_name = "BSA"
save_raw_images = 0

# VCSEL parameters
check_bias           = 1    # Bias current to check the alignment
vcsel_chip           = "johannes" # Which chip is being used
vcsel_biases         = [3, 3,3]  # mA

# Camera and measurement interval
measurement_time     = 3600   # Measurement time in seconds
measurement_interval = 5      # Take a picture every x sec
exposure_time        = 0.01   # Exposure time in sec
frame_average        = 10

# Find detection lines before measurement
find_det_lines       = 1    # Run live capturing to find detection line
find_line_biased     = 1    # Run live capturing with biased VCSEL


verbose_printing     = 1        # Flag for printing

[keithley2400]
Type = "keithley2400"       # The specific type of unit
GPIB_address = "24"
