#Std units: mA, V, mW, nm

[measurement]
Type = "spr_no_lam_sweep"
Save_folder = "C:/Users/Mindaugas Juodenas/Documents/GitHub/SPR_measurements/" 
DC_unit = "keithley2400"    # Refers to the [] below only
V_max = 5                   # Max allowed voltaged

SPR_measurement_name = "erik_testing"

Current              = 1    # Current for measurement
Check_bias           = 1    # Bias current to check the alignment
Measurement_time     = 100 # Measurement time in seconds
Measurement_interval = 10   # Take a picture every x sec
Exposure_time        = 0.01 # Exposure time in sec

Find_det_lines       = 1    # Run live capturing to find detection line
Find_line_biased     = 1    # Run live capturing with biased VCSEL

Verbose_printing     = 1        # Flag for printing

[keithley2400]
Type = "keithley2400"       # The specific type of unit
GPIB_address = "24"

[hamamatsu_s2281]
Type = "hamamatsu_s2281"    # The specific type of unit
GPIB_address = "9"

[INT_sphere]
Type = "ophir_IS6_D_UV"
Range = 2
Min_measure_time = 0.2      # How long to wait between new data to arrive from sphere
Wavelength = 5

[powercube]
Type = "powercube"
Port = "com4"


# Avaliable ranges for IS6-D-UV
# 0    auto
# 1    1 W
# 2    300 mW
# 3    30 mW
# 4    3 mW
# 5    300 uW
# 6    30 uW
# 7    3 uW

# Avaliable wavelengths for IS6-D-UV
# 0    940 nm
# 1    300 nm
# 2    633 nm
# 3    543 nm
# 4    870 nm
# 5    850 nm
