# Std units: mA, V, mW, nm


[measurement]
type = 'test_measurement'
name = 'test_1'

# Camera and measurement interval
measurement_time            = 15000   # Measurement time in seconds
measurement_interval        = 1.5      # Take a picture every x sec
measurement_subinterval     = 0.001  
exposure_time               = 0.1   # Exposure time in sec
frame_average_buffer        = 10
frame_average               = 10

verbose_level     = 1        # 1. Verbose 0. Off

