# Std units: mA, V, mW, nm


[measurement]
Type = 'test_measurement'

# Camera and measurement interval
measurement_time            = 15000   # Measurement time in seconds
measurement_interval        = 1.5      # Take a picture every x sec
measurement_subinterval     = 0.001  
exposure_time               = 0.1   # Exposure time in sec
frame_average_buffer        = 10
frame_average               = 10

verbose_printing     = 1        # Flag for printing

