[measurement]
type = "ipv"
DC_unit = "keith"
P_unit = "INT_sphere"
I_start = 0
I_end = 0.005
V_max = 5
P_cutoff = 0
datapoints = 50



[keith]
type = "keithley"
address = "24"

[INT_sphere]
type = "INT_sphere"
range = 2
min_measure_time = 0.2
