[measurement]
Type = "ipv"
Save_folder = "c:/LABDATA"
DC_unit = "keithley2400"
P_unit = "INT_sphere"
V_max = 5
Rollover_threshold = 0  # Stops measurement when power < rollover_threshold * maxpower
Rollover_min = 0.1      # Doesn't do rollover check on values lower than this
Current = [[0.001, 0.0001, 0.005], [0.005, 0.0005, 0.015]]  # [min, step, max]

[keithley2400]
GPIB_address = "24"

[INT_sphere]
Range = 2
Min_measure_time = 0.2  #How long to wait between new data to arrive from sphere
Wavelength = 5

[powercube]
Port = "com4"