#Std units: mA, V, mW, nm

[measurement]
Type = "ipv_diode"
Save_folder = "c:/LABDATA"
DC_unit = "keithley2400"    # Refers to the [] below only
P_unit = "hamamatsu_s2281"
V_max = 6
Current = [[0, 0.01, 1], [1, 0.02, 12]]
#Current = [[0, 0.005, 1], [1, 0.01, 10]]  # mA [min, step, max]
#Current = [[0, 1, 5]]

# Optional arguments
Rollover_threshold = 0.85 # Stops measurement when power < rollover_threshold * maxpower
Rollover_min = 1        # Doesn't do rollover check on power values lower than this
Plot_interval = 1000      # Update plot every nth measurement
Verbose_printing = 1    # Flag for printing
Keep_plot = 1           # To keep plot after measurement is done

[keithley2400]
Type = "keithley2400"   # The specific type of unit
GPIB_address = "24"

[hamamatsu_s2281]
Type = "hamamatsu_s2281"   # The specific type of unit
GPIB_address = "9"

[INT_sphere]
Type = "ophir_IS6_D_UV"
Range = 2
Min_measure_time = 0.2  # How long to wait between new data to arrive from sphere
Wavelength = 5

[powercube]
Type = "powercube"
Port = "com4"


# Avaliable ranges for IS6-D-UV
# 0    auto
# 1    1 W
# 2    300 mW
# 3    30 mW
# 4    3 mW
# 5    300 uW
# 6    30 uW
# 7    3 uW

# Avaliable wavelengths for IS6-D-UV
# 0    940 nm
# 1    300 nm
# 2    633 nm
# 3    543 nm
# 4    870 nm
# 5    850 nm
