#Std units: mA, V, mW, nm

[measurement]
Type = "spr_lam_sweep"
Save_folder = "C:/Users/Mindaugas Juodenas/Documents/GitHub/SPR_measurements/" 
DC_unit = "keithley2400"    # Refers to the [] below only
V_max = 5                   # Max allowed voltaged

SPR_measurement_name = "erik_testing"

Current              = 1    # Current for measurement
Check_bias           = 1    # Bias current to check the alignment
Measurement_time     = 100  # Measurement time in seconds
Measurement_interval = 10   # Take a picture every x sec
Exposure_time        = 0.03 # Exposure time in sec
swept_bias           = [[0.5, 0.05, 1]]

Find_det_lines       = 0    # Run live capturing to find detection line
Find_line_biased     = 1    # Run live capturing with biased VCSEL

Verbose_printing     = 1        # Flag for printing

[keithley2400]
Type = "keithley2400"       # The specific type of unit
GPIB_address = "24"
